version: 1
validation: sovereign
default_denom: ubet
accounts:
  - name: alice
    coins:
      - 200000000ubet
  - name: bob
    coins:
      - 100000000ubet
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
    - 100000ubet
validators:
  - name: alice
    bonded: 100000000ubet
  - name: validator1
    bonded: 200000000ubet
  - name: validator2
    bonded: 100000000ubet
